##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.ksqldb-server:0.7.0 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/etc/confluent/docker/run"
# config omitted for the moment
# COPY ./conteco/ksql-server/base/* /etc/ksql/
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="ksqldb-server" \
    CONTECO_NAME="base" \
    CONTECO_TAG="0.7.0" \
    CONTECO_BASE="external.ksqldb-server:0.7.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="ksqldb-server" \
      io.vcweb.name="base" \
      io.vcweb.tag="0.7.0" \
      io.vcweb.base="external.ksqldb-server:0.7.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="ksqldb-server.base - Conteco " \
      io.vcweb.description="Confluent KSQLDB Server base image, using default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.ksqldb-server.base --help" 
##### END image.base/Dockerfile/env-labels-footer #####
