#!/usr/bin/env bash

export CONTECO_LABEL="ksqldb_server.base - Conteco "
export CONTECO_DESCRIPTION="Confluent ksqlDB Server base image, using default configuration."

export CONTECO_TYPE="ksqldb_server"
export CONTECO_NAME="base"
export CONTECO_TAG="0.12.0"

export CONTECO_BASE="external.ksqldb_server:0.12.0"
export CONTECO_BUILD="image-base"
